# Este arquivo é usado para configurar as ferramentas de análise e formatação do Dart.
# Para mais informações: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

# A seção a seguir configura o formatador do Dart.
dart_format:
  # Define o comprimento da linha para 120 caracteres.
  # O padrão é 80.
  line_length: 120