# Este arquivo é usado para configurar as ferramentas de análise e formatação do Dart.
# Para mais informações: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    lines_longer_than_80_chars: false

formatter:  
  page_width: 120
  trailing_commas: preserve


